name: Monorepo Workflow

on:
  push:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Check for changes in the 'client' directory
      - name: Check for changes in client
        id: client_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            client:
              - 'client/**'

      
      # Check for changes in the 'client' directory
      - name: Check for changes in server
        id: client_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            server:
              - 'server/**'
       
  client: 
    needs: check-changes
    runs-on: ubuntu-latest
    if: steps.check-changes.outputs.client == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.before }}

      - name: checking inside client
        run : |
          echo "Checking inside client"
          ls -la client

  server:
    needs: check-changes
    runs-on: ubuntu-latest
    if: steps.check-changes.outputs.server == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.before }}

      - name: checking inside server
        run : |
          echo "Checking inside server"
          ls -la server
      
