name: Monorepo Workflow

on:
  push:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.client_changes.outputs.client }}
      server_changed: ${{ steps.server_changes.outputs.server }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Check for changes in the 'client' directory
      - name: Check for changes in client
        id: client_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            client:
              - 'client/**'

      # Check for changes in the 'server' directory
      - name: Check for changes in server
        id: server_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            server:
              - 'server/**'

  client:
    needs: check-changes
    if: needs.check-changes.outputs.client_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Run client tests
        run: echo "Inside client tests"


  server:
    needs: check-changes
    if: needs.check-changes.outputs.server_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Run server tests
        run: echo "Inside server tests"
