name: Monorepo Workflow

on:
  push:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.client_changes.outputs.client }}
      server_changed: ${{ steps.server_changes.outputs.server }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Check for changes in the 'client' directory
      - name: Check for changes in client
        id: client_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            client:
              - 'client/**'

      # Check for changes in the 'server' directory
      - name: Check for changes in server
        id: server_changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'server/**'

  client:
    needs: check-changes
    if: needs.check-changes.outputs.client_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Creating docker Image
        run: |
          cd client
          docker build -t meabhisingh/client_sample .

      - name: Pushing docker image to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push meabhisingh/client_sample
          docker logout

  server:
    needs: check-changes
    if: needs.check-changes.outputs.server_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Creating docker Image
        run: |
          cd server
          docker build -t meabhisingh/server_sample .

      - name: Pushing docker image to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push meabhisingh/server_sample
          docker logout
