name: Monorepo Workflow

on:
  push:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Check for changes in the 'client' directory
      - name: Check for changes in client
        id: client_changes
        run: echo "Changes in client"

      # Check for changes in the 'server' directory
      - name: Check for changes in server
        id: server_changes
        run: echo "Changes in server"

